# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: bitnami/postgresql
    restart: always
    environment:
      POSTGRES_USER: puck
      POSTGRES_PASSWORD: S3CReTP4SSW0RDpuck
    ports:
      - 5444:5432
    volumes:
      - postgresql:/bitnami/postgresql

volumes:
  postgresql:
