version: '3.3'
services:
  binancebot:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports:
      - 80:8083
    image: nyamkamunhjin/binance-bot-v3
