-- CreateEnum
CREATE TYPE "EventStatus" AS ENUM ('REQUEST_SENT', 'CHEF_ACCEPTED', 'CHEF_ARRIVED', 'FOOD_PREPARING', 'FOOD_READY', 'FOOD_SERVING', 'FOOD_SERVED', 'CHEF_LEFT');

-- AlterTable
ALTER TABLE "Event" ADD COLUMN     "status" "EventStatus" NOT NULL DEFAULT 'REQUEST_SENT';
