app = "srve-backend"

kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  dockerfile = "./srve-backend.Dockerfile"

[build.args]
  DATABASE_URL = "postgresql://postgres:3gA3I9t2g3KAYc4@srve-database.fly.dev:5432/postgres"

[env]
  NODE_ENV = "production"
  PORT = 80
  DATABASE_URL = "postgresql://postgres:3gA3I9t2g3KAYc4@srve-database.fly.dev:5432/postgres"
  JWT_SECRET = "SECRET_JWT_KEY"
  GOOGLE_CLIENT_ID = "160751823241-20vr3vm2lopaptr2b2rqsfc3bbscumqj.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET = "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"
  FACEBOOK_APP_ID = "498260331991310"
  FACEBOOK_APP_SECRET = "4dcfaf8f2cebb39acc56c4360fa42878"
  REDIS_URL = "redis://default:a0734303365f496caaab09c809f21f88@fly-srve-redis.upstash.io"
  MINIO_ACCESSKEY = "srve"
  MINIO_BUCKETNAME = "srve"
  MINIO_SECRETKEY = "EOAtiJr8laBkT7zSAeQpbDBieAFCPCP9"
  MINIO_ENDPOINT = "srve-minio.fly.dev:9000"
  MINIO_PORT = "9000"
  TWILIO_ACCOUNT_SID="ACf4deefe90266334234dccafe997d1e3e"
  TWILIO_AUTH_TOKEN = "44783ac5dad5eeb2b527bcbe66a78e59"
  TWILIO_PHONE_NUMBER = "+13205372283"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 80
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 80

  [[services.ports]]
    handlers = ["http"]
    port = 443
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 5
    timeout = "100s"
