name: Update Image and Redeploy container

on:
  push:
    branches:
      - main  # Replace with your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Login to DockerHub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and tag Docker image
        run: |
          docker build -t nyamkamunhjin/binance-bot-v2:latest .
        working-directory: ./

      - name: Push Docker image to DockerHub
        run: |
          docker push nyamkamunhjin/binance-bot-v2:latest
        working-directory: ./

  update-container:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    - name: run update script
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: trade.munkhjin.fun
        username: munkhjin
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: | 
          ./update.sh